language: R
sudo: false
os: linux
dist: xenial

addons:
  apt:
    packages:
      - time

jdk:
  - openjdk11

cache:
  directories:
    - /home/travis/R/
    - /usr/local/lib/R/site-library

env:
  global:
    - RELEASE_PATH=/tmp/release.tar.gz
    - BUILD_PATH=$(mktemp -d)
  matrix:
    - ISBUILD=no
    - ISBUILD=yes

install:
  - ./src/compile.sh
  - Rscript src/plots/requirements.r

script: >
  [[ $ISBUILD == yes ]] && ./run-all.sh ${TEST_COUNT:-50} || :

after_success: >
  [[ $ISBUILD == yes ]] && {
      cat /proc/cpuinfo > data/cpuinfo.txt
      ( cd src/plots && Rscript -e 'lintr::lint_package()' )

      .travis/build_index.sh plots data > index.html
      mv data plots *.md *.html $BUILD_PATH

      tar -cf $RELEASE_PATH $BUILD_PATH
  } || :

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: ${RELEASE_PATH}
    file_glob: true
    skip_cleanup: true
    draft: false
    on:
      branch: master
      condition: $ISBUILD = yes

  - provider: pages
    local-dir: $BUILD_PATH
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
      condition: $ISBUILD = yes
    edge:
      branch: v1.8.47
