language: R
sudo: false
os: linux
dist: xenial

addons:
  apt:
    packages:
      - time

jdk:
  - openjdk11

cache:
  directories:
    - /home/travis/R/
    - /usr/local/lib/R/site-library

env:
  global:
    - RELEASE_PATH=/tmp/release.tar.gz
    - BUILD_PATH=$(mktemp)

install:
  - cat /proc/cpuinfo > data/cpuinfo.txt
  - ./src/compile.sh
  - Rscript src/plots/requirements.r

script:
  - ./run-all.sh

after_success:
  - ( cd src/plots && Rscript -e 'lintr::lint_package()' )
  - mv data plots *.md $BUILD_PATH
  - tar -cf $RELEASE_PATH $BUILD_PATH/*

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: ${RELEASE_PATH}
    file_glob: true
    skip_cleanup: true
    draft: false
    on:
      branch: master

  - provider: pages
    local-dir: $BUILD_PATH
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
    edge:
      branch: v1.8.47
